name: Songs to PDF

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: List files in songs directory
        run: ls songs || exit 1

      - name: Update CPAN (optional)
        run: |
          cpan
          cpan install CPAN
          reload cpan

      - name: Install Perl
        run: |
          sudo apt-get update || exit 1
          sudo apt-get install -y perl || exit 1

      - name: Install ChordPro prerequisites with apt
        run: |
          sudo apt-get install -y libpdf-api2-perl libimage-info-perl || exit 1

      - name: Install ChordPro reference implementation
        run: |
          sudo cpan install ChordPro

      - name: Check for songs directory
        run: |
          test -d songs || exit 1

      - name: Check for valid ChordPro files
        run: |
          find songs -name "*.chordpro" -print0 | xargs -0 chordpro --validate || exit 1

      - name: Generate PDF
        run: |
          mkdir -p pdf_output
          for file in songs/*.chordpro; do
            chordpro "$file" -o "pdf_output/$(basename "$file" .chordpro).pdf" || exit 1
          done

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: chordpro-pdf
          path: ${{ env.WORKSPACE }}/pdf_output/
