name: Songs to PDF

on:
  # push:
    # branches: [ main ]
  # pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List files in songs directory
        run: |
          echo "Found the following song files:"
          ls songs || exit 1

      - name: Test CPAN configuration with sudo
        run: |
          sudo cpan install chordpro
          chordpro --version
        shell: bash  # Ensure bash for variable export

      - name: Export CPAN environment variables
        run: |
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "PERL5LIB=$PERL5LIB" >> $GITHUB_ENV
          echo "PERL_LOCAL_LIB_ROOT=$PERL_LOCAL_LIB_ROOT" >> $GITHUB_ENV
          echo "PERL_MB_OPT=$PERL_MB_OPT" >> $GITHUB_ENV
          echo "PERL_MM_OPT=$PERL_MM_OPT" >> $GITHUB_ENV

      - name: Check for songs directory and ChordPro files
        run: |
          test -d songs || exit 1
          find songs -name "*.chordpro" -print0 || exit 1

      - name: Validate ChordPro files
        run: |
          # Install the "File::Spec" module (if not already present)
          cpan install File::Spec
      
          # Loop through each `.chordpro` file in the "songs" directory
          for file in songs/*.chordpro; do
            # Use "File::Spec" to construct the full path with environment variables
            full_path=$(perl -MFile::Spec -e 'print File::Spec::rel2abs("$file", $ENV{PWD})')
      
            # Validate the file using "chordpro --validate"
            chordpro --validate "$full_path" || exit 1
      
            # Optionally: Print validation output for debugging
            # echo "Validation output for $file:"
            # cat "$full_path.validate.log"
          done


      - name: Generate PDF
        run: |
          mkdir -p pdf_output
          # for file in songs/*.chordpro; do
          #  chordpro "$file" -o "pdf_output/$(basename "$file" .chordpro).pdf" || exit 1
          # done
          chordpro --filelist songs/*.chordpro --output=pdf_output/songbook.pdf

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: chordpro-pdf
          path: ${{ env.WORKSPACE }}/pdf_output/
